// packages/create-zama-app/templates/vue/src/components/Navbar.vue
<template>
  <nav class="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
    <div class="container mx-auto px-4">
      <div class="flex h-16 items-center justify-between">
        <!-- Logo -->
        <div class="flex items-center space-x-4">
          <h1 class="text-xl font-bold">FHEVM Vue</h1>
        </div>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex items-center space-x-4">
          <!-- Network Selector -->
          <div v-if="walletStore.isConnected" class="flex items-center space-x-2">
            <span class="text-sm text-muted-foreground">Network:</span>
            <select
              :value="walletStore.currentNetwork || ''"
              @change="handleNetworkChange"
              class="text-sm border rounded px-2 py-1 bg-background"
            >
              <option value="hardhat">Hardhat Local</option>
              <option value="sepolia">Sepolia</option>
            </select>
          </div>

          <!-- Wallet Info -->
          <div v-if="walletStore.isConnected" class="flex items-center space-x-2">
            <div class="text-sm">
              <div class="font-medium">{{ formatAddress(walletStore.userAddress) }}</div>
              <div class="text-muted-foreground">
                {{ NETWORKS[walletStore.currentNetwork || 'hardhat']?.name }}
              </div>
            </div>
          </div>

          <!-- Connect/Disconnect Button -->
          <Button
            v-if="!walletStore.isConnected"
            @click="walletStore.connectWallet"
            :disabled="walletStore.isConnecting"
            class="flex items-center space-x-2"
          >
            <Wallet class="h-4 w-4" />
            <span>{{ walletStore.isConnecting ? 'Connecting...' : 'Connect Wallet' }}</span>
          </Button>

          <Button
            v-else
            @click="walletStore.disconnectWallet"
            variant="outline"
            class="flex items-center space-x-2"
          >
            <LogOut class="h-4 w-4" />
            <span>Disconnect</span>
          </Button>

          <!-- Theme Toggle -->
          <Button
            @click="themeStore.toggleTheme"
            variant="ghost"
            size="icon"
            class="flex items-center justify-center"
          >
            <Sun v-if="themeStore.isDark" class="h-4 w-4" />
            <Moon v-else class="h-4 w-4" />
          </Button>

          <!-- Documentation Link -->
          <Button
            as="a"
            href="https://docs.zama.ai/fhevm"
            target="_blank"
            rel="noopener noreferrer"
            variant="outline"
            class="flex items-center space-x-2"
          >
            <ExternalLink class="h-4 w-4" />
            <span>Docs</span>
          </Button>
        </div>

        <!-- Mobile Menu Button -->
        <div class="md:hidden">
          <Button
            @click="mobileMenuOpen = !mobileMenuOpen"
            variant="ghost"
            size="icon"
          >
            <Menu class="h-4 w-4" />
          </Button>
        </div>
      </div>

      <!-- Mobile Menu -->
      <div v-if="mobileMenuOpen" class="md:hidden border-t py-4 space-y-4">
        <!-- Wallet Connection -->
        <div v-if="!walletStore.isConnected">
          <Button
            @click="handleMobileConnect"
            :disabled="walletStore.isConnecting"
            class="w-full flex items-center justify-center space-x-2"
          >
            <Wallet class="h-4 w-4" />
            <span>{{ walletStore.isConnecting ? 'Connecting...' : 'Connect Wallet' }}</span>
          </Button>
        </div>

        <div v-else class="space-y-4">
          <!-- Wallet Info -->
          <div class="text-center">
            <div class="font-medium">{{ formatAddress(walletStore.userAddress) }}</div>
            <div class="text-sm text-muted-foreground">
              {{ NETWORKS[walletStore.currentNetwork || 'hardhat']?.name }}
            </div>
          </div>

          <!-- Network Selector -->
          <div>
            <label class="block text-sm font-medium mb-2">Network:</label>
            <select
              :value="walletStore.currentNetwork || ''"
              @change="handleNetworkChange"
              class="w-full border rounded px-3 py-2 bg-background"
            >
              <option value="hardhat">Hardhat Local</option>
              <option value="sepolia">Sepolia</option>
            </select>
          </div>

          <!-- Disconnect Button -->
          <Button
            @click="handleMobileDisconnect"
            variant="outline"
            class="w-full flex items-center justify-center space-x-2"
          >
            <LogOut class="h-4 w-4" />
            <span>Disconnect</span>
          </Button>
        </div>

        <!-- Theme Toggle -->
        <Button
          @click="themeStore.toggleTheme"
          variant="ghost"
          class="w-full flex items-center justify-center space-x-2"
        >
          <Sun v-if="themeStore.isDark" class="h-4 w-4" />
          <Moon v-else class="h-4 w-4" />
          <span>{{ themeStore.isDark ? 'Light Mode' : 'Dark Mode' }}</span>
        </Button>

        <!-- Documentation Link -->
        <Button
          as="a"
          href="https://docs.zama.ai/fhevm"
          target="_blank"
          rel="noopener noreferrer"
          variant="outline"
          class="w-full flex items-center justify-center space-x-2"
        >
          <ExternalLink class="h-4 w-4" />
          <span>Documentation</span>
        </Button>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useWalletStore } from '@/stores/wallet'
import { useThemeStore } from '@/stores/theme'
import { NETWORKS } from '@/utils/fhevm'
import Button from '@/components/ui/Button.vue'
import { 
  Wallet, 
  LogOut, 
  Sun, 
  Moon, 
  ExternalLink, 
  Menu 
} from 'lucide-vue-next'

const walletStore = useWalletStore()
const themeStore = useThemeStore()
const mobileMenuOpen = ref(false)

function formatAddress(address: string): string {
  if (!address) return ''
  return `${address.slice(0, 6)}...${address.slice(-4)}`
}

async function handleNetworkChange(event: Event): Promise<void> {
  const target = event.target as HTMLSelectElement
  const networkKey = target.value as keyof typeof NETWORKS
  
  if (networkKey && walletStore.currentNetwork !== networkKey) {
    const success = await walletStore.switchToNetwork(networkKey)
    if (!success) {
      // Reset select to current network if switch failed
      target.value = walletStore.currentNetwork || 'hardhat'
    }
  }
}

async function handleMobileConnect(): Promise<void> {
  await walletStore.connectWallet()
  mobileMenuOpen.value = false
}

function handleMobileDisconnect(): void {
  walletStore.disconnectWallet()
  mobileMenuOpen.value = false
}
</script>

// packages/create-zama-app/templates/next/components/navbar.tsx
"use client"

import { useState, useEffect } from 'react';
import { BrowserProvider } from 'ethers';
import { useTheme } from 'next-themes';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { detectNetwork, switchNetwork, NETWORKS, type NetworkName } from '@/lib/fhevm';
import { Moon, Sun, ExternalLink, Wallet } from 'lucide-react';

interface NavbarProps {
  onWalletConnect?: (provider: BrowserProvider, address: string) => void;
}

export function Navbar({ onWalletConnect }: NavbarProps) {
  const { theme, setTheme } = useTheme();
  const [isConnected, setIsConnected] = useState(false);
  const [address, setAddress] = useState<string>('');
  const [network, setNetwork] = useState<NetworkName | null>(null);
  const [provider, setProvider] = useState<BrowserProvider | null>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    checkConnection();
    
    if (window.ethereum) {
      window.ethereum.on('accountsChanged', handleAccountsChanged);
      window.ethereum.on('chainChanged', handleChainChanged);
    }

    return () => {
      if (window.ethereum) {
        window.ethereum.removeListener('accountsChanged', handleAccountsChanged);
        window.ethereum.removeListener('chainChanged', handleChainChanged);
      }
    };
  }, []);

  const checkConnection = async () => {
    if (!window.ethereum) return;

    try {
      const provider = new BrowserProvider(window.ethereum);
      const accounts = await provider.listAccounts();
      
      if (accounts.length > 0) {
        const address = accounts[0].address;
        setIsConnected(true);
        setAddress(address);
        setProvider(provider);
        
        const detectedNetwork = await detectNetwork(provider);
        setNetwork(detectedNetwork);
        
        onWalletConnect?.(provider, address);
      }
    } catch (error) {
      console.error('Failed to check connection:', error);
    }
  };

  const handleAccountsChanged = (accounts: string[]) => {
    if (accounts.length === 0) {
      setIsConnected(false);
      setAddress('');
      setProvider(null);
      setNetwork(null);
    } else {
      setAddress(accounts[0]);
      checkConnection();
    }
  };

  const handleChainChanged = () => {
    window.location.reload();
  };

  const connectWallet = async () => {
    if (!window.ethereum) {
      alert('Please install MetaMask to use this application');
      return;
    }

    try {
      const provider = new BrowserProvider(window.ethereum);
      await provider.send('eth_requestAccounts', []);
      
      const signer = await provider.getSigner();
      const address = await signer.getAddress();
      
      setIsConnected(true);
      setAddress(address);
      setProvider(provider);
      
      const detectedNetwork = await detectNetwork(provider);
      setNetwork(detectedNetwork);
      
      onWalletConnect?.(provider, address);
    } catch (error) {
      console.error('Failed to connect wallet:', error);
    }
  };

  const handleNetworkSwitch = async (targetNetwork: NetworkName) => {
    if (!provider) return;
    
    try {
      const chainId = NETWORKS[targetNetwork].chainId;
      await switchNetwork(chainId);
    } catch (error) {
      console.error('Failed to switch network:', error);
    }
  };

  const formatAddress = (addr: string) => {
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
  };

  const toggleTheme = () => {
    setTheme(theme === 'dark' ? 'light' : 'dark');
  };

  if (!mounted) {
    return null;
  }

  return (
    <nav className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          {/* Logo */}
          <div className="flex items-center space-x-2">
            <div className="text-2xl font-bold text-primary">🔐</div>
            <span className="text-xl font-semibold">Zama FHEVM</span>
          </div>

          {/* Center - Network Info */}
          <div className="flex items-center space-x-4">
            {isConnected && network && (
              <div className="flex items-center space-x-2">
                <div className="text-sm text-muted-foreground">Network:</div>
                <div className="flex space-x-2">
                  <Button
                    variant={network === 'hardhat' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => handleNetworkSwitch('hardhat')}
                  >
                    Hardhat Local
                  </Button>
                  <Button
                    variant={network === 'sepolia' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => handleNetworkSwitch('sepolia')}
                  >
                    Sepolia
                  </Button>
                </div>
              </div>
            )}
          </div>

          {/* Right side */}
          <div className="flex items-center space-x-4">
            {/* Theme Toggle */}
            <div className="flex items-center space-x-2">
              <Sun className="h-4 w-4" />
              <Switch
                checked={theme === 'dark'}
                onCheckedChange={toggleTheme}
              />
              <Moon className="h-4 w-4" />
            </div>

            {/* Wallet Connection */}
            {isConnected ? (
              <div className="flex items-center space-x-2">
                <div className="text-sm text-muted-foreground">
                  {formatAddress(address)}
                </div>
                <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              </div>
            ) : (
              <Button onClick={connectWallet} className="flex items-center space-x-2">
                <Wallet className="h-4 w-4" />
                <span>Connect Wallet</span>
              </Button>
            )}

            {/* Zama Docs Link */}
            <Button
              variant="outline"
              size="sm"
              onClick={() => window.open('https://docs.zama.ai/protocol/examples/', '_blank')}
              className="flex items-center space-x-2"
            >
              <span>View Zama Docs</span>
              <ExternalLink className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </nav>
  );
}
