// packages/create-zama-app/templates/vue/src/App.vue
<template>
  <div class="min-h-screen bg-background text-foreground">
    <!-- Navigation -->
    <Navbar />

    <!-- Main Content -->
    <main class="container mx-auto px-4 py-8">
      <!-- Hero Section -->
      <section class="text-center py-16">
        <h1 class="text-4xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
          FHEVM Vue Template
        </h1>
        <p class="text-xl md:text-2xl text-muted-foreground mb-8 max-w-3xl mx-auto">
          Build privacy-preserving dApps with Fully Homomorphic Encryption on the blockchain
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <Button
            v-if="!walletStore.userAddress"
            @click="walletStore.connectWallet"
            size="lg"
            class="flex items-center space-x-2"
          >
            <Wallet class="h-5 w-5" />
            <span>Connect Wallet</span>
          </Button>
          <Button
            variant="outline"
            size="lg"
            class="flex items-center space-x-2"
            @click="openDocumentation"
          >
            <ExternalLink class="h-5 w-5" />
            <span>View Documentation</span>
          </Button>
        </div>
      </section>

      <!-- Wallet Connection Prompt -->
      <section v-if="!walletStore.userAddress" class="py-16">
        <Card class="max-w-md mx-auto text-center">
          <CardHeader>
            <CardTitle class="flex items-center justify-center space-x-2">
              <Wallet class="h-6 w-6" />
              <span>Connect Your Wallet</span>
            </CardTitle>
            <CardDescription>
              Connect your wallet to start interacting with FHEVM smart contracts
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button
              @click="walletStore.connectWallet"
              class="w-full flex items-center justify-center space-x-2"
            >
              <Wallet class="h-5 w-5" />
              <span>Connect Wallet</span>
            </Button>
          </CardContent>
        </Card>
      </section>

      <!-- FHEVM Counter Demo -->
      <section v-else class="py-16">
        <div class="text-center mb-12">
          <h2 class="text-3xl font-bold mb-4">🔐 Encrypted Counter Demo</h2>
          <p class="text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience the power of Fully Homomorphic Encryption with this interactive counter.
            All operations are performed on encrypted data while maintaining complete privacy.
          </p>
        </div>
        <Counter />
      </section>

      <!-- Features Grid -->
      <section class="py-16">
        <div class="text-center mb-12">
          <h2 class="text-3xl font-bold mb-4">Why Choose FHEVM?</h2>
          <p class="text-lg text-muted-foreground">
            Build the next generation of privacy-preserving applications
          </p>
        </div>
        <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card class="text-center">
            <CardHeader>
              <Shield class="h-12 w-12 mx-auto mb-4 text-blue-600" />
              <CardTitle>Privacy First</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Perform computations on encrypted data without revealing sensitive information
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="text-center">
            <CardHeader>
              <Zap class="h-12 w-12 mx-auto mb-4 text-yellow-600" />
              <CardTitle>High Performance</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Optimized FHE operations with minimal gas costs and fast execution times
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="text-center">
            <CardHeader>
              <Code class="h-12 w-12 mx-auto mb-4 text-green-600" />
              <CardTitle>Developer Friendly</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Easy-to-use APIs and comprehensive tooling for seamless development
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="text-center">
            <CardHeader>
              <Globe class="h-12 w-12 mx-auto mb-4 text-purple-600" />
              <CardTitle>Multi-Network</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Deploy on multiple networks with built-in support for testnet and mainnet
              </CardDescription>
            </CardContent>
          </Card>
        </div>
      </section>

      <!-- Resources Section -->
      <section class="py-16">
        <div class="text-center mb-12">
          <h2 class="text-3xl font-bold mb-4">Resources & Documentation</h2>
          <p class="text-lg text-muted-foreground">
            Everything you need to get started with FHEVM development
          </p>
        </div>
        <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card class="hover:shadow-lg transition-shadow cursor-pointer" @click="openLink('https://docs.zama.ai/fhevm')">
            <CardHeader>
              <BookOpen class="h-8 w-8 mb-2 text-blue-600" />
              <CardTitle class="text-lg">FHEVM Docs</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Complete documentation for FHEVM development
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="hover:shadow-lg transition-shadow cursor-pointer" @click="openLink('https://github.com/zama-ai/fhevm')">
            <CardHeader>
              <Github class="h-8 w-8 mb-2 text-gray-600" />
              <CardTitle class="text-lg">GitHub</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Source code, examples, and community contributions
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="hover:shadow-lg transition-shadow cursor-pointer" @click="openLink('https://docs.zama.ai/fhevm/tutorials')">
            <CardHeader>
              <GraduationCap class="h-8 w-8 mb-2 text-green-600" />
              <CardTitle class="text-lg">Tutorials</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Step-by-step guides and practical examples
              </CardDescription>
            </CardContent>
          </Card>

          <Card class="hover:shadow-lg transition-shadow cursor-pointer" @click="openLink('https://discord.gg/fhe-org')">
            <CardHeader>
              <MessageCircle class="h-8 w-8 mb-2 text-purple-600" />
              <CardTitle class="text-lg">Discord</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Join our community for support and discussions
              </CardDescription>
            </CardContent>
          </Card>
        </div>
      </section>
    </main>

    <!-- Footer -->
    <footer class="border-t bg-muted/50 py-8">
      <div class="container mx-auto px-4 text-center">
        <p class="text-muted-foreground">
          Built with ❤️ using FHEVM, Vue.js, and Tailwind CSS
        </p>
        <p class="text-sm text-muted-foreground mt-2">
          © 2024 Zama. All rights reserved.
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { useWalletStore } from '@/stores/wallet'
import Navbar from '@/components/Navbar.vue'
import Counter from '@/components/Counter.vue'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardDescription from '@/components/ui/CardDescription.vue'
import CardContent from '@/components/ui/CardContent.vue'
import Button from '@/components/ui/Button.vue'
import {
  Wallet,
  ExternalLink,
  Shield,
  Zap,
  Code,
  Globe,
  BookOpen,
  Github,
  GraduationCap,
  MessageCircle
} from 'lucide-vue-next'

const walletStore = useWalletStore()

function openDocumentation(): void {
  window.open('https://docs.zama.ai/fhevm', '_blank')
}

function openLink(url: string): void {
  window.open(url, '_blank')
}
</script>

// packages/create-zama-app/templates/next/app/page.tsx
"use client"

import { useState, useEffect } from 'react';
import { BrowserProvider } from 'ethers';
import { Navbar } from '@/components/navbar';
import { Counter } from '@/components/counter';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Shield, Zap, Code, Globe, ExternalLink } from 'lucide-react';

export default function Home() {
  const [provider, setProvider] = useState<BrowserProvider | null>(null);
  const [userAddress, setUserAddress] = useState<string>('');

  useEffect(() => {
    // Check if wallet is already connected
    checkWalletConnection();
  }, []);

  const checkWalletConnection = async () => {
    if (typeof window !== 'undefined' && window.ethereum) {
      try {
        const provider = new BrowserProvider(window.ethereum);
        const accounts = await provider.listAccounts();
        
        if (accounts.length > 0) {
          setProvider(provider);
          setUserAddress(accounts[0].address);
        }
      } catch (error) {
        console.error('Failed to check wallet connection:', error);
      }
    }
  };

  const handleWalletConnect = (newProvider: BrowserProvider, address: string) => {
    setProvider(newProvider);
    setUserAddress(address);
  };

  const handleWalletDisconnect = () => {
    setProvider(null);
    setUserAddress('');
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar 
        onWalletConnect={handleWalletConnect}
        onWalletDisconnect={handleWalletDisconnect}
        provider={provider}
        userAddress={userAddress}
      />
      
      <main className="container mx-auto px-4 py-8">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold tracking-tight mb-4">
            Welcome to <span className="text-primary">FHEVM</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Build privacy-preserving decentralized applications with Fully Homomorphic Encryption
          </p>
        </div>

        {/* Wallet Connection Prompt */}
        {!provider && (
          <Card className="max-w-md mx-auto mb-8">
            <CardHeader>
              <CardTitle>🔗 Connect Your Wallet</CardTitle>
              <CardDescription>
                Connect your wallet to start interacting with FHEVM smart contracts
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Use the "Connect Wallet" button in the navigation bar to get started.
              </p>
            </CardContent>
          </Card>
        )}

        {/* Counter Demo */}
        <div className="mb-12">
          <Counter provider={provider} userAddress={userAddress} />
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <Card>
            <CardHeader>
              <Shield className="h-8 w-8 text-primary mb-2" />
              <CardTitle className="text-lg">Privacy First</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Perform computations on encrypted data without revealing sensitive information
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Zap className="h-8 w-8 text-primary mb-2" />
              <CardTitle className="text-lg">High Performance</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Optimized FHEVM implementation for efficient encrypted computations
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Code className="h-8 w-8 text-primary mb-2" />
              <CardTitle className="text-lg">Developer Friendly</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Easy-to-use APIs and comprehensive documentation for rapid development
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Globe className="h-8 w-8 text-primary mb-2" />
              <CardTitle className="text-lg">Multi-Network</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Support for multiple networks including local development and testnets
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Resources Section */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>📚 Learn More</CardTitle>
            <CardDescription>
              Explore resources to help you build with FHEVM
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              <Button variant="outline" className="justify-start" asChild>
                <a 
                  href="https://docs.zama.ai/fhevm" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center space-x-2"
                >
                  <span>FHEVM Documentation</span>
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
              
              <Button variant="outline" className="justify-start" asChild>
                <a 
                  href="https://github.com/zama-ai/fhevm" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center space-x-2"
                >
                  <span>GitHub Repository</span>
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
              
              <Button variant="outline" className="justify-start" asChild>
                <a 
                  href="https://docs.zama.ai/fhevm/tutorials" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center space-x-2"
                >
                  <span>Tutorials</span>
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
              
              <Button variant="outline" className="justify-start" asChild>
                <a 
                  href="https://discord.gg/fhe-org" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center space-x-2"
                >
                  <span>Community Discord</span>
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <footer className="text-center text-sm text-muted-foreground">
          <p>
            Built with ❤️ using{' '}
            <a 
              href="https://nextjs.org" 
              target="_blank" 
              rel="noopener noreferrer"
              className="underline hover:text-foreground"
            >
              Next.js
            </a>
            {' '}and{' '}
            <a 
              href="https://docs.zama.ai/fhevm" 
              target="_blank" 
              rel="noopener noreferrer"
              className="underline hover:text-foreground"
            >
              FHEVM
            </a>
          </p>
        </footer>
      </main>
    </div>
  );
}
